"use client";
import { useEffect, useState } from "react";
const projects = [["After the Rain","Feature film · Producer / Art direction","2024","https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=85"],["Neon Quiet","Short film · Writer / Production design","2023","https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=85"],["Moth Season","Series · Visual development","2023","https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&w=1200&q=85"],["Objects in a Room","Photography · Still life studies","2022","https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85"],["Blue Hour Notes","Photography · Sydney / Seoul","2022","https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=85"],["Small Gestures","Graphic design · Identity system","2021","https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=85"],["Paper Worlds","Illustration · Boards / visual essay","2021","https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1200&q=85"],["The Long Take","Feature film · Production design","2020","https://images.unsplash.com/photo-1574267432553-4b4628081c31?auto=format&fit=crop&w=1200&q=85"]] as const;
const nav=["About","Film","Photo","Design","Contact"];
export default function Home(){const [view,setView]=useState("About");const [menu,setMenu]=useState(false);const [filmIndex,setFilmIndex]=useState<number|null>(null);const [cursor,setCursor]=useState({x:0,y:0});const go=(v:string)=>{setView(v);setMenu(false);setFilmIndex(null)};useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setFilmIndex(null)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);return <main className="site-shell" onPointerMove={e=>setCursor({x:e.clientX,y:e.clientY})} style={{"--cursor-x":`${cursor.x}px`,"--cursor-y":`${cursor.y}px`} as React.CSSProperties}><div className="cursor-dot"/><header className="topbar"><button className="wordmark" onClick={()=>go("About")}>Y / X<span>—</span></button><div className="topbar-right"><span className="availability"><i/> Available for select projects · 2026</span><button className="menu-toggle" onClick={()=>setMenu(!menu)}>{menu?"Close":"Menu"}</button></div></header><nav className={`menu-panel ${menu?"is-open":""}`}>{nav.map((n,i)=><button key={n} className={view===n?"active":""} onClick={()=>go(n)}><span>0{i+1}</span>{n}</button>)}</nav>
{view==="About"&&<section className="home-canvas"><p className="eyebrow">Independent creative studio / 2026</p><h1>Stories<br/><em>with a pulse.</em></h1><div className="home-cube"/><div className="home-map">{nav.map((n,i)=><button key={n} onClick={()=>go(n)}><b>0{i+1}</b>{n}<span>↗</span></button>)}</div><p className="home-note">Producer · Production designer · Writer<br/>Building cinematic worlds across film, image and form.</p></section>}
{view==="Film"&&<section className="module-page film-page"><div className="module-heading"><p className="eyebrow">02 — Film works / drag left-right</p><h2>Worlds made<br/><em>for the frame.</em></h2></div><div className="film-rail">{projects.map((p,i)=><button className={`film-card film-card-${i%3}`} key={p[0]} onClick={()=>setFilmIndex(i)}><div className="film-image" style={{backgroundImage:`url(${p[3]})`}}/><span>0{i+1}</span><strong>{p[0]}</strong><small>{p[2]} · View project ↗</small></button>)}</div></section>}
{view==="Photo"&&<section className="module-page photo-page"><div className="module-heading"><p className="eyebrow">03 — Photography / move your cursor</p><h2>Collected<br/><em>light.</em></h2></div><div className="photo-pile">{projects.slice(1,8).map((p,i)=><div className={`pile-card pile-${i}`} key={p[0]} style={{backgroundImage:`url(${p[3]})`}}><span>{p[0]}</span></div>)}</div></section>}
{view==="Design"&&<section className="module-page design-page"><div className="module-heading"><p className="eyebrow">04 — Graphic design & illustration</p><h2>Handmade<br/><em>systems.</em></h2></div><div className="design-field"><div className="design-image design-a" style={{backgroundImage:`url(${projects[5][3]})`}}><span>Identity / 2021</span></div><div className="design-image design-b" style={{backgroundImage:`url(${projects[6][3]})`}}><span>Paper worlds / 2021</span></div><div className="design-image design-c" style={{backgroundImage:`url(${projects[3][3]})`}}><span>Set graphics / 2022</span></div></div></section>}
{view==="Contact"&&<section className="module-page contact-page"><p className="eyebrow">05 — Contact</p><h2>Start with<br/><em>a feeling.</em></h2><a className="contact-email" href="mailto:hello@yixuan.studio">hello@yixuan.studio ↗</a></section>}
{filmIndex!==null&&<section className="film-detail"><button className="transition-close" onClick={() => setFilmIndex(null)}>Close <span>↗</span></button><div className="detail-visual" style={{backgroundImage:`url(${projects[filmIndex][3]})`}}/><div className="detail-copy"><p className="eyebrow">{projects[filmIndex][1]}</p><h2>{projects[filmIndex][0]}</h2><p>A cinematic study in atmosphere, rhythm and physical detail. Treatment, stills and production notes for this project.</p><div className="detail-controls"><button onClick={()=>setFilmIndex((filmIndex+projects.length-1)%projects.length)}>← Previous</button><button onClick={()=>setFilmIndex((filmIndex+1)%projects.length)}>Next →</button></div></div></section>}
</main>}
